### get all persons

GET http://localhost:3001/api/persons

### Get the person with id 3

GET http://localhost:3001/api/persons/3

### Get the person with id 5 and see error

GET http://localhost:3001/api/persons/5

### Delete the person with id 2

DELETE http://localhost:3001/api/persons/2

### Test successful creation of contact

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Gabriel Ong",
    "number": "96626967"
}

### Test no number

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Gabriel Ong",
    "number": null
}

### Test no name

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": null,
    "number": 96626967
}

### Test name already exist
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Mary Poppendick",
    "number": "39-23-643122"
}

### Test Logging
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Lisa Marttinen",
    "number": "040-23456"
}