### create a note
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "Test note of my backend functionality for note",
    "important": false
}

### Test invalid note
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": null,
    "important": false
}

### Test put functionality
PUT http://localhost:3001/api/notes/610677f334be9925bc049e90
content-type: application/json

{
    "content": "you can modify the content of notes with put",
    "important": false
}


### get all notes
GET http://localhost:3001/api/notes

### Retrieve a note
GET http://localhost:3001/api/notes/610677f334be9925bc049e90


### Delete a note
DELETE http://localhost:3001/api/notes/60e0645ad000d4268156f52b